name: Build app

on:
  push:
  pull_request:
  schedule:
  - cron: '0 6 * * 1' # Run every Monday at 06:00 (UTC)
  
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sersoft-gmbh/xcodebuild-action@v1
